// src/main/handlers/authHandlers.js
import { ipcMain, BrowserWindow, session } from "electron";
import fs from "fs";
import path from "path";
import os from "os";

// Mesmo caminho do utils.js
const cookiesPath = path.join(
  os.homedir(),
  "AppData",
  "Roaming",
  "meu-projeto",
  "cookies.txt",
);

function exportCookiesToFile(cookies) {
  const lines = ["# Netscape HTTP Cookie File", "# Generated by Waves", ""];

  for (const cookie of cookies) {
    // Pula cookies com valores problemáticos para o formato Netscape
    if (!cookie.name || cookie.value === undefined) continue;

    const domain = cookie.domain.startsWith(".")
      ? cookie.domain
      : `.${cookie.domain}`;
    const includeSubdomains = "TRUE"; // sempre TRUE — yt-dlp exige isso
    const secure = cookie.secure ? "TRUE" : "FALSE";
    const expires = cookie.expirationDate
      ? Math.floor(cookie.expirationDate)
      : 2147483647;

    // Sanitiza o valor: remove tabs e quebras de linha que corrompem o formato
    const value = String(cookie.value)
      .replace(/\t/g, "%09")
      .replace(/\r/g, "")
      .replace(/\n/g, "%0A");

    lines.push(
      [
        domain,
        includeSubdomains,
        cookie.path || "/",
        secure,
        expires,
        cookie.name,
        value,
      ].join("\t"),
    );
  }

  const content = lines.join("\n") + "\n";

  try {
    fs.mkdirSync(path.dirname(cookiesPath), { recursive: true });
    fs.writeFileSync(cookiesPath, content, "utf-8");
    console.log(
      `✅ cookies.txt exportado: ${cookiesPath} (${lines.length - 3} cookies)`,
    );
  } catch (err) {
    console.error("❌ Erro ao exportar cookies.txt:", err);
  }
}

export function registerAuthHandlers() {
  ipcMain.handle("google:login-external", async () => {
    const prevLoginSession = session.fromPartition("persist:google-login");
    await prevLoginSession.clearStorageData({ storages: ["cookies"] });

    return new Promise((resolve) => {
      const loginWin = new BrowserWindow({
        width: 500,
        height: 680,
        title: "Entrar com Google",
        webPreferences: {
          partition: "persist:google-login",
          nodeIntegration: false,
          contextIsolation: true,
        },
      });

      loginWin.loadURL(
        "https://accounts.google.com/ServiceLogin?service=youtube",
      );

      const targetSession = session.fromPartition("persist:google-login");

      const cookieCheck = setInterval(async () => {
        const cookies = await targetSession.cookies.get({
          domain: ".google.com",
        });
        const loggedIn = cookies.some(
          (c) => c.name === "SID" || c.name === "SSID" || c.name === "HSID",
        );

        if (loggedIn) {
          clearInterval(cookieCheck);

          // Navega para o YouTube para gerar cookies de sessão do YouTube
          loginWin.webContents.loadURL("https://www.youtube.com");

          // Aguarda o YouTube carregar antes de fechar
          loginWin.webContents.once("did-finish-load", async () => {
            await new Promise((r) => setTimeout(r, 2000)); // tempo para cookies serem escritos
            loginWin.close();
            resolve(true);
          });
        }
      }, 1500);

      loginWin.on("closed", () => {
        clearInterval(cookieCheck);
        resolve(false);
      });
    });
  });

  ipcMain.handle("google:import-cookies", async () => {
    const loginSession = session.fromPartition("persist:google-login");
    const youtubeSession = session.fromPartition("persist:youtube");

    // Limpa cookies antigos do webview
    await youtubeSession.clearStorageData({ storages: ["cookies"] });

    const domains = [".youtube.com", ".google.com", "accounts.google.com"];
    const allCookies = [];

    for (const domain of domains) {
      const cookies = await loginSession.cookies.get({ domain });
      console.log(`🍪 [${domain}] encontrados: ${cookies.length} cookies`);

      for (const cookie of cookies) {
        if (
          cookie.name.startsWith("__Host-") ||
          cookie.name.startsWith("__Secure-")
        )
          continue;

        try {
          await youtubeSession.cookies.set({
            url: `https://${cookie.domain.replace(/^\./, "")}`,
            name: cookie.name,
            value: cookie.value,
            domain: cookie.domain,
            path: cookie.path,
            secure: cookie.secure,
            httpOnly: cookie.httpOnly,
            expirationDate: cookie.expirationDate,
          });
          allCookies.push(cookie);
        } catch (err) {
          console.warn(`⚠️ Cookie ignorado [${cookie.name}]:`, err.message);
        }
      }
    }

    // Exporta para cookies.txt no formato Netscape (usado pelo yt-dlp)
    exportCookiesToFile(allCookies);

    console.log(`✅ Total de cookies copiados: ${allCookies.length}`);
    return true;
  });

  ipcMain.handle("google:logout", async () => {
    const youtubeSession = session.fromPartition("persist:youtube");
    await youtubeSession.clearStorageData({
      storages: ["cookies", "localstorage", "sessionstorage", "cachestorage"],
    });
    return true;
  });
}
